name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chromedriver@latest

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew build
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
          CHROME_DRIVER_PATH: ${{ steps.setup-chromedriver.outputs.chromedriver-path }}
          CHROME_HEADLESS: true