name: Java CI with Gradle

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    
    # - name: Set up JDK 21
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin' # Adjust the distribution if necessary
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Test with Gradle
      run: ./gradlew test
